#!/usr/bin/env python3
"""Independent release-manifest verifier (VER-CORE 4.1/4.2/4.3, Section 12 step 2). Stdlib, fail-closed.

Verifies, against the anchored ownership map and the live tree, with no trust in generator output:
  1  schemas strict for ownership, manifest, order, references, renderers; dispositions and releases to
     Step-2 depth (top-level keys plus a minimal guard on any present row), the full per-row and per-kind
     schemas deferred to Step 4 (check_release_delta, where release and disposition rows are consumed);
  2  the build-time inversion assertion (completeness, no-strays, disjointness, exclusion cross-checks,
     concern-2 zero-tracked), recomputed via gen_manifest's validated loader (the house import-reuse
     pattern; the verdict is recomputed from inputs, never read from generated bytes);
  3  the ABSOLUTE-MINIMUM-CLASS table (declared HERE, the verifier; 4.2);
  4  release-version equals VERSION; genesis is boolean and consistent with releases.toml (2.5);
  5  exact SOURCES set equality plus per-row byte size and raw-byte SHA-256 (no decode, no normalize);
  6  filesystem semantics over the concern-1 extent: lstat every component; a symlink anywhere, a hard
     link (st_nlink > 1), a non-regular file, a case-fold or NFC/NFD collision, or CANNOT-EVALUATE is a
     FAIL, never a clean pass (4.3);
  7  the ARTIFACTS roster recomputed from the renderer declaration inputs; every digest re-hashed; the
     CLAUDE.md managed-block digest recomputed (bytes outside the block never affect the verdict);
  8  TREE digest recomputation; ROOT recomputed from the exact manifest bytes and byte-compared to
     .aiqt/release/root.txt; the announce snippet regenerated and byte-compared;
  9  the references registry schema with pipeline identity and the ALIAS GATE (5.3);
 10  the dispositions record schema (6.5), header-or-rows: the common mandatory fields, a known kind, a
     unique id, and no unknown top-level key (per-kind field validation deferred to Step 4, where used);
 11  the declared order record equals the operative ordering constants in gen_rules.py (TIER_FACETS,
     CIA_FACETS, apex prjint1), so the record cannot drift from operative code.

NOT here (named residue): the site/downloads recomputation is owned by those generators' own drift
gates in the same roster; adopter-side set-equality runs over the concern-3 extent per the
adopter-experience spec; the manifest detects ACCIDENT, not tamper (4.4).

  check_manifest.py [--root DIR]      the release-side gate
  check_manifest.py --self-test       synthetic fixtures assert every leg fires

Exit convention: 0 clean; 1 a well-formed disagreement (digest, size, set, TREE, ROOT, snippet,
artifact, managed-block, order-consistency drift); 2 malformed/unreadable input, an assertion or
schema violation, a minimum-class violation, a filesystem-semantics violation, or any cannot-evaluate.
"""
import hashlib
import os
import stat
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    sys.exit("error: check_manifest.py requires Python 3.11+ (tomllib).")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _gen_common import repo_root, load_toml  # noqa: E402
import gen_manifest  # noqa: E402  reuse the validated loader/expansion; recompute, never trust output

HEX64 = frozenset("0123456789abcdef")

# The verifier-carried ABSOLUTE-MINIMUM-CLASS table (4.2): first match wins; the final row is the
# category default. Strength order: pack-immutable > managed-block > manifest-self = derived >
# adopter-state = archive. The manifest itself must be EXACTLY manifest-self.
CLASS_STRENGTH = {"pack-immutable": 4, "managed-block": 3, "manifest-self": 2, "derived": 2,
                  "adopter-state": 1, "archive": 1}
MINIMUM_CLASSES = (
    (".aiqt/manifest.toml", "manifest-self", "exact"),
    ("CLAUDE.md", "managed-block", "min"),
    (".aiqt/release/**", "derived", "min"),
    ("site/downloads/**", "derived", "min"),
    ("**", "pack-immutable", "min"),   # the category default: every other in-scope pack path
)

DISPOSITION_KINDS = {"behaviour-neutral", "strengthened", "default-correction", "class-change",
                     "version-impact", "renderer-semantics"}


def _min_for(path):
    for sel, minimum, mode in MINIMUM_CLASSES:
        if sel == "**" or path == sel or (sel.endswith("/**") and path.startswith(sel[:-2])):
            return minimum, mode
    raise AssertionError("unreachable: the '**' default row always matches")


def apply_minimums(classes):
    """FAIL (GateError -> exit 2) any assignment weaker than its declared minimum; binds every map at
    every release including genesis and first add (4.2). Shared with gen_manifest."""
    for path, cls in classes.items():
        minimum, mode = _min_for(path)
        if mode == "exact":
            if cls != minimum:
                raise gen_manifest.GateError("{}: class must be exactly {!r}, got {!r}".format(
                    path, minimum, cls))
        elif CLASS_STRENGTH[cls] < CLASS_STRENGTH[minimum]:
            raise gen_manifest.GateError("{}: class {!r} is weaker than the absolute minimum {!r}; the "
                                         "minimum is never dispositionable away".format(
                                             path, cls, minimum))


def _hex_ok(value):
    return isinstance(value, str) and len(value) == 64 and set(value) <= HEX64


def load_manifest(root):
    """Strict manifest schema (4.1): exact top-level keys, exact row keys, validated types and digests,
    no duplicate paths, sources sorted bytewise. Violations raise GateError (exit 2)."""
    try:
        data = load_toml(root / gen_manifest.MANIFEST_REL)
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        raise gen_manifest.GateError("cannot read the manifest ({})".format(exc))
    top = {"format-version", "release-version", "genesis", "tree-sha256", "sources", "artifacts"}
    if set(data) != top:
        raise gen_manifest.GateError("manifest: top-level keys must be exactly {}".format(sorted(top)))
    if data["format-version"] != 1 or not isinstance(data["genesis"], bool):
        raise gen_manifest.GateError("manifest: format-version must be 1 and genesis a real boolean")
    if not _hex_ok(data["tree-sha256"]):
        raise gen_manifest.GateError("manifest: tree-sha256 is not 64 lowercase hex")
    seen = set()
    for row in data["sources"]:
        if set(row) != {"path", "bytes", "sha256"}:
            raise gen_manifest.GateError("manifest sources row keys must be exactly path/bytes/sha256")
        if not isinstance(row["bytes"], int) or isinstance(row["bytes"], bool) or row["bytes"] < 0 \
                or not _hex_ok(row["sha256"]):
            raise gen_manifest.GateError("manifest sources row for {!r} is malformed".format(
                row.get("path")))
        if row["path"] in seen:
            raise gen_manifest.GateError("manifest: duplicate sources path {!r}".format(row["path"]))
        seen.add(row["path"])
    for row in data["artifacts"]:
        allowed = {"artifact-id", "path", "kind", "sha256", "block-id"}
        if set(row) - allowed or {"artifact-id", "path", "kind", "sha256"} - set(row):
            raise gen_manifest.GateError("manifest artifacts row keys are malformed")
        if not _hex_ok(row["sha256"]):
            raise gen_manifest.GateError("manifest artifacts row for {!r} has a malformed digest".format(
                row.get("artifact-id")))
    paths = [r["path"] for r in data["sources"]]
    if paths != sorted(paths):
        raise gen_manifest.GateError("manifest: sources are not sorted bytewise by path")
    return data


def walk_semantics(root, classes):
    """The 4.3 filesystem-semantics leg over the concern-1 extent: lstat every path component beneath
    root; any symlink, hard link, non-regular file, or unanswerable question is GateError (exit 2)."""
    checked_dirs = set()
    for path in classes:
        parts = path.split("/")
        cur = root
        for comp in parts[:-1]:
            cur = cur / comp
            if cur in checked_dirs:
                continue
            st = os.lstat(cur)  # OSError propagates to the caller's fail-closed map
            if stat.S_ISLNK(st.st_mode) or not stat.S_ISDIR(st.st_mode):
                raise gen_manifest.GateError("{}: intermediate {} is a symlink or not a directory"
                                             .format(path, cur.name))
            checked_dirs.add(cur)
        st = os.lstat(root / path)
        if stat.S_ISLNK(st.st_mode) or not stat.S_ISREG(st.st_mode):
            raise gen_manifest.GateError("{}: not a regular non-symlink file".format(path))
        if st.st_nlink > 1:
            raise gen_manifest.GateError("{}: hard link (st_nlink={})".format(path, st.st_nlink))


def check_order_record(root, findings):
    """Leg 11: the declared order record equals the operative constants (gen_rules.TIER_FACETS,
    CIA_FACETS, apex prjint1). Malformed record raises (exit 2); a well-formed disagreement is a
    finding (exit 1)."""
    import gen_rules
    try:
        data = load_toml(root / ".aiqt" / "core" / "order.toml")
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        raise gen_manifest.GateError("cannot read order.toml ({})".format(exc))
    if data.get("format-version") != 1 or data.get("apex-corpus-id") != "prjint1":
        raise gen_manifest.GateError("order.toml: format-version 1 and apex-corpus-id 'prjint1' required")
    extra = set(data) - {"format-version", "apex-corpus-id", "precedence-tier", "presentation-order"}
    if extra:  # F-237: an unknown top-level key (e.g. a typo) is a schema FAIL, never silently tolerated.
        raise gen_manifest.GateError("order.toml: unknown top-level key(s): {}".format(
            ", ".join(sorted(extra))))
    try:
        declared = {int(t["rank"]): sorted(t["members"]) for t in data.get("precedence-tier", [])}
        for t in data.get("precedence-tier", []):
            if not isinstance(t.get("members-are-equal"), bool):
                raise gen_manifest.GateError("order.toml: members-are-equal must be a boolean")
    except (KeyError, TypeError, ValueError) as exc:
        raise gen_manifest.GateError("order.toml: a precedence-tier row is malformed ({})".format(exc))
    operative = {int(k): sorted(v) for k, v in gen_rules.TIER_FACETS.items()}
    if declared != operative:
        findings.append("order.toml precedence tiers disagree with the operative gen_rules.TIER_FACETS")
    pres = data.get("presentation-order", {})
    if sorted(pres.get("security-facets", [])) != sorted(gen_rules.CIA_FACETS):
        findings.append("order.toml security facets disagree with the operative gen_rules.CIA_FACETS")


def check_references(root):
    """Leg 9: the 5.3 registry schema and the alias gate. Violations raise (exit 2)."""
    try:
        data = load_toml(root / ".aiqt" / "core" / "references.toml")
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        raise gen_manifest.GateError("cannot read references.toml ({})".format(exc))
    if data.get("format-version") != 1 or not isinstance(data.get("quorum"), int) \
            or isinstance(data.get("quorum"), bool) or data["quorum"] < 1:
        raise gen_manifest.GateError("references.toml: format-version 1 and integer quorum >= 1 required")
    extra = set(data) - {"format-version", "quorum", "reference"}
    if extra:  # F-237: an unknown top-level key (e.g. a `quroum` typo) is a schema FAIL.
        raise gen_manifest.GateError("references.toml: unknown top-level key(s): {}".format(
            ", ".join(sorted(extra))))
    pipelines = set()
    for row in data.get("reference", []):
        if set(row) != {"location", "retrieval-method", "derivation", "pipeline-id",
                        "independence-basis"}:
            raise gen_manifest.GateError("references.toml: a row's keys are not the exact 5.3 schema")
        if row["derivation"] not in ("independent", "mirror"):
            raise gen_manifest.GateError("references.toml: derivation must be independent|mirror")
        if row["derivation"] == "independent":
            if row["pipeline-id"] in pipelines:  # the ALIAS GATE: never silently count aliases once
                raise gen_manifest.GateError("references.toml: two independent entries share pipeline "
                                             "identity {!r}".format(row["pipeline-id"]))
            pipelines.add(row["pipeline-id"])
    # F-237 / spec 5.3: quorum must be SATISFIABLE. Quorum is counted over distinct independent pipeline
    # identities; a quorum exceeding the count available can never be met, so it is a schema FAIL, not a
    # verdict a later run silently fails.
    if data["quorum"] > len(pipelines):
        raise gen_manifest.GateError("references.toml: quorum {} exceeds the {} distinct independent "
                                     "pipeline identit(ies) available; an unsatisfiable quorum (5.3)"
                                     .format(data["quorum"], len(pipelines)))


def check_dispositions(root):
    """Leg 10: the 6.5 dispositions record schema (header-or-rows). Zero rows is valid, and is the whole
    Step-2 state (the record is header-only until the first dispositioned change). At Step 2 each row is
    checked for the COMMON mandatory fields, a known kind, a unique id, and no unknown top-level key.
    DEFERRED to Step 4 (the release-delta gate, spec 6.5), recorded not built here: PER-KIND field
    validation (each kind's own required fields, e.g. the default-correction evidence reference of 6.6),
    which the release-delta gate performs where disposition rows are first consumed. Violations raise
    (exit 2)."""
    try:
        data = load_toml(root / ".aiqt" / "core" / "dispositions.toml")
    except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
        raise gen_manifest.GateError("cannot read dispositions.toml ({})".format(exc))
    if data.get("format-version") != 1:
        raise gen_manifest.GateError("dispositions.toml: format-version must be exactly 1")
    extra = set(data) - {"format-version", "disposition"}
    if extra:  # F-237: an unknown top-level key is a schema FAIL, never silently tolerated.
        raise gen_manifest.GateError("dispositions.toml: unknown top-level key(s): {}".format(
            ", ".join(sorted(extra))))
    ids = set()
    for row in data.get("disposition", []):
        common = {"id", "release", "kind", "impact", "rationale"}
        if not common <= set(row):
            raise gen_manifest.GateError("dispositions.toml: a row is missing a mandatory field")
        if row["kind"] not in DISPOSITION_KINDS:
            raise gen_manifest.GateError("dispositions.toml: unknown kind {!r}".format(row["kind"]))
        if row["id"] in ids:
            raise gen_manifest.GateError("dispositions.toml: duplicate id {!r}".format(row["id"]))
        ids.add(row["id"])


def run(root, anchored=False):
    findings = []
    try:
        # 1 + 2 + 3: schemas, the inversion assertion, minimums (all recomputed; exit 2 on violation).
        exclusions, release, namespace, binary_set = gen_manifest.load_ownership(root)
        tracked = gen_manifest.git_tracked(root)
        classes, _ = gen_manifest.classify(tracked, exclusions, release, namespace, root)
        gen_manifest.cross_check_exclusions(root, exclusions)
        apply_minimums(classes)
        gen_manifest.check_output_modes(root)  # F-236: the four outputs are index-mode 100644 (defence in depth).
        manifest = load_manifest(root)

        # 4: version and genesis consistency.
        version = gen_manifest.read_version(root)
        if manifest["release-version"] != version:
            findings.append("manifest release-version {!r} does not equal VERSION {!r}".format(
                manifest["release-version"], version))
        if manifest["genesis"] != gen_manifest.read_genesis(root):
            raise gen_manifest.GateError("manifest genesis flag disagrees with the releases.toml row "
                                         "count (2.5); a genesis manifest requires a zero-row record")

        # 5: exact SOURCES set equality + raw-byte re-hash.
        expected = sorted(p for p, c in classes.items()
                          if p not in (gen_manifest.MANIFEST_REL, gen_manifest.ROOT_REL,
                                       gen_manifest.SNIPPET_REL) and c != "managed-block")
        declared = [r["path"] for r in manifest["sources"]]
        for missing in sorted(set(expected) - set(declared)):
            findings.append("SOURCES missing the tracked pack path {}".format(missing))
        for extra in sorted(set(declared) - set(expected)):
            findings.append("SOURCES lists {} which is not an expected member".format(extra))
        for row in manifest["sources"]:
            if row["path"] not in classes:
                continue  # already a finding above
            try:
                data = (root / row["path"]).read_bytes()
            except OSError as exc:
                raise gen_manifest.GateError("cannot read SOURCES member {} ({})".format(row["path"], exc))
            if len(data) != row["bytes"] or hashlib.sha256(data).hexdigest() != row["sha256"]:
                findings.append("{}: bytes/sha256 disagree with the working tree".format(row["path"]))

        # 6: filesystem semantics (exit 2 on violation).
        walk_semantics(root, classes)

        # 7: artifacts recomputed from inputs.
        renderers = gen_manifest.load_renderers(root)
        expected_rows = gen_manifest.build_artifacts(root, classes, renderers)
        got = {(r.get("artifact-id"), r.get("path"), r.get("kind"), r.get("sha256"),
                r.get("block-id")) for r in manifest["artifacts"]}
        want = {(r.get("artifact-id"), r.get("path"), r.get("kind"), r.get("sha256"),
                 r.get("block-id")) for r in expected_rows}
        for row in sorted(want - got):
            findings.append("ARTIFACTS missing or drifted: {}".format(row[0]))
        for row in sorted(got - want):
            findings.append("ARTIFACTS lists an unexpected or stale row: {}".format(row[0]))

        # 8: TREE, ROOT, snippet recomputation.
        tree = hashlib.sha256("".join("{}\t{}\n".format(r["path"], r["sha256"])
                                      for r in manifest["sources"]).encode("utf-8")).hexdigest()
        if tree != manifest["tree-sha256"]:
            findings.append("tree-sha256 does not recompute from the SOURCES rows")
        try:
            manifest_raw = (root / gen_manifest.MANIFEST_REL).read_bytes()
            root_disk = (root / gen_manifest.ROOT_REL).read_bytes()
            snippet_disk = (root / gen_manifest.SNIPPET_REL).read_bytes()
        except OSError as exc:
            raise gen_manifest.GateError("cannot read a derived release artifact ({})".format(exc))
        root_hex = hashlib.sha256(manifest_raw).hexdigest()
        if root_disk != "sha256:{}\n".format(root_hex).encode():
            findings.append("root.txt does not recompute from the manifest bytes")
        want_snippet = "aiqt-guardrails release {}\nroot sha256:{}\n".format(version, root_hex).encode()
        if snippet_disk != want_snippet:
            findings.append("announce-snippet.txt does not recompute from manifest plus version")

        # 9 + 10 + 11: the 5.3 registry, the 6.5 dispositions record, and the order record.
        check_references(root)
        check_dispositions(root)
        check_order_record(root, findings)

        if anchored:
            # 5.7 observed-run recording: deferred at this release (quorum default 1, anchor deferred).
            pass
    except gen_manifest.GateError as exc:
        print("error: {}; fail-closed".format(exc), file=sys.stderr)
        return 2
    except (OSError, UnicodeError, tomllib.TOMLDecodeError, ValueError, KeyError, TypeError) as exc:
        print("error: cannot evaluate ({}: {}); fail-closed".format(type(exc).__name__, exc),
              file=sys.stderr)
        return 2
    if findings:
        print("FAIL: {} finding(s)".format(len(findings)))
        for f in findings:
            print("  - " + f)
        return 1
    print("PASS: manifest verified: scope by inversion, {} sources set-equal and re-hashed, artifacts, "
          "tree, root, and snippet recomputed clean".format(len(manifest["sources"])))
    return 0


def main():
    args = sys.argv[1:]
    if "--self-test" in args:
        return self_test_main()
    root = repo_root()
    if "--root" in args:
        i = args.index("--root")
        if i + 1 >= len(args):
            print("usage: check_manifest.py [--root DIR] [--anchored] | --self-test", file=sys.stderr)
            return 2
        root = Path(args[i + 1]).resolve()
    return run(root, anchored="--anchored" in args)


# --- self-test ----------------------------------------------------------------------------------------
# Reuses gen_manifest's synthetic git fixture builder, generates the four outputs, then asserts each leg
# fires:
#   (a) a clean fixture passes (exit 0);
#   (b) a wrong SOURCES byte size/hash -> exit 1; a missing SOURCES row -> exit 1;
#   (c) a below-minimum class (a pack path assigned adopter-state) -> exit 2;
#   (d) a genesis flag disagreeing with a non-empty releases.toml -> exit 2;
#   (e) a symlinked SOURCES member and a hard link each -> exit 2;
#   (f) an alias-gate duplicate pipeline-id in references.toml -> exit 2;
#   (g) a managed-block digest drift with unchanged surrounding bytes -> exit 1, while a surrounding-bytes
#       change with an unchanged block still passes (exit 0);
#   (h) an order record disagreeing with the operative constants -> exit 1.

def self_test_main():
    import io
    import shutil
    import tempfile
    from contextlib import redirect_stdout, redirect_stderr

    gm = gen_manifest
    if __import__("subprocess").run(["git", "--version"], capture_output=True).returncode != 0:
        print("SELF-TEST ERROR: git is unavailable; fail-closed", file=sys.stderr)
        return 2

    def check_quiet(root):
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            try:
                return run(root)
            except SystemExit as exc:
                return "raised SystemExit({!r})".format(exc.code)

    def gen_quiet(root):
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            return gm.run(root, check=False)

    def _fresh(name, **kw):
        base = gm._build_fixture(Path(tmp) / name, **kw)
        if base is not None:
            gen_quiet(base)
        return base

    try:
        tmp = Path(tempfile.mkdtemp(prefix="aiqt-check-manifest-selftest-"))
    except OSError as exc:
        print("SELF-TEST ERROR: no writable temporary directory: {}".format(exc), file=sys.stderr)
        return 2
    failures = []
    try:
        # (a) clean fixture passes.
        clean = _fresh("clean")
        if clean is None:
            print("SELF-TEST ERROR: cannot init a git fixture; fail-closed", file=sys.stderr)
            return 2
        if check_quiet(clean) != 0:
            failures.append("clean fixture expected exit 0")

        # (b) a wrong SOURCES byte on disk -> exit 1 (bytes/sha256 disagree).
        b = _fresh("badbyte")
        (b / "src.txt").write_text("MUTATED source\n", encoding="utf-8")
        if check_quiet(b) != 1:
            failures.append("a working-tree byte disagreeing with SOURCES expected exit 1")

        # (b2) F-238: a missing SOURCES row must fail SOLELY on set-equality (leg 5), not incidentally on
        #      the tree/root/snippet recompute (leg 8). Drop the src.txt row, then recompute tree-sha256,
        #      root.txt, and the snippet CONSISTENTLY so leg 8 stays clean and the ONLY discrepancy is the
        #      absent tracked member. A mutant deleting the leg-5 set-equality loops then makes this
        #      fixture PASS, proving leg 5 is what catches the drop.
        m = _fresh("missrow")
        text = (m / gm.MANIFEST_REL).read_text(encoding="utf-8")
        block = '[[sources]]\npath = "src.txt"\n'
        idx = text.find(block)
        end = text.find("\n\n", idx)
        m_text = text[:idx] + text[end + 2:]
        parsed = tomllib.loads(m_text)
        tree = hashlib.sha256("".join("{}\t{}\n".format(r["path"], r["sha256"])
                                      for r in parsed["sources"]).encode("utf-8")).hexdigest()
        m_text = m_text.replace('tree-sha256 = "{}"'.format(parsed["tree-sha256"]),
                                'tree-sha256 = "{}"'.format(tree))
        (m / gm.MANIFEST_REL).write_text(m_text, encoding="utf-8")
        manifest_raw = (m / gm.MANIFEST_REL).read_bytes()
        root_hex = hashlib.sha256(manifest_raw).hexdigest()
        (m / gm.ROOT_REL).write_text("sha256:{}\n".format(root_hex), encoding="utf-8")
        version = gm.read_version(m)
        (m / gm.SNIPPET_REL).write_text(
            "aiqt-guardrails release {}\nroot sha256:{}\n".format(version, root_hex), encoding="utf-8")
        if check_quiet(m) != 1:
            failures.append("a missing SOURCES row expected exit 1 SOLELY on set-equality (F-238)")

        # (c) a below-minimum class: build clean (outputs written), then swap the map so a pack path
        #     (src.txt, minimum pack-immutable) is assigned the weaker 'derived'. The checker's
        #     apply_minimums must fail closed (exit 2).
        low = _fresh("lowclass")
        (low / ".aiqt" / "core" / "ownership.toml").write_text(
            gm._OWN_BASE.replace('path = "src.txt"\nclass = "pack-immutable"',
                                 'path = "src.txt"\nclass = "derived"') + gm._OWN_TAIL,
            encoding="utf-8")
        if check_quiet(low) != 2:
            failures.append("a below-minimum class (src.txt -> derived) expected exit 2")

        # (d) genesis flag vs a non-empty releases.toml -> exit 2. Add a VALID [[release]] row (version +
        #     commit_sha) after generation, so the row passes read_genesis's minimal guard and it is the
        #     genesis-flag DISAGREEMENT (manifest genesis=true beside a non-empty record) that fails closed.
        g = _fresh("genesis")
        (g / ".aiqt" / "core" / "releases.toml").write_text(
            'format-version = 1\n\n[[release]]\nversion = "1.0.0"\ncommit_sha = "deadbeef"\n',
            encoding="utf-8")
        if check_quiet(g) != 2:
            failures.append("genesis=true beside a non-empty releases.toml expected exit 2")

        # (e) a symlinked SOURCES member -> exit 2.
        sy = _fresh("symlink")
        tgt = sy / "src.txt"
        tgt.unlink()
        try:
            tgt.symlink_to(sy / "out.txt")
            symlink_ok = True
        except OSError:
            symlink_ok = False
        if symlink_ok and check_quiet(sy) != 2:
            failures.append("a symlinked SOURCES member expected exit 2 (4.3 filesystem semantics)")
        # a hard link (st_nlink > 1) -> exit 2.
        hl = _fresh("hardlink")
        try:
            (hl / "src.txt").unlink()
            os.link(hl / "out.txt", hl / "src.txt")  # replace src with a hard link to out
            hard_ok = True
        except OSError:
            hard_ok = False
        if hard_ok:
            # src.txt now has nlink 2; rewrite it so bytes still match? bytes differ (out content). The
            # walk fires before the hash leg would matter; exit 2 is the semantics violation.
            if check_quiet(hl) != 2:
                failures.append("a hard-linked SOURCES member expected exit 2 (st_nlink > 1)")

        # (f) an alias-gate duplicate pipeline-id -> exit 2.
        al = _fresh("alias")
        (al / ".aiqt" / "core" / "references.toml").write_text(
            'format-version = 1\nquorum = 1\n\n'
            '[[reference]]\nlocation = "a"\nretrieval-method = "git-tag"\nderivation = "independent"\n'
            'pipeline-id = "P"\nindependence-basis = "x"\n\n'
            '[[reference]]\nlocation = "b"\nretrieval-method = "git-tag"\nderivation = "independent"\n'
            'pipeline-id = "P"\nindependence-basis = "y"\n', encoding="utf-8")
        if check_quiet(al) != 2:
            failures.append("an alias-gate duplicate pipeline-id expected exit 2")

        # (g) managed-block digest drift with unchanged surroundings -> exit 1; a surroundings-only change
        #     with an unchanged block still passes.
        mb = _fresh("mblock")
        raw = (mb / "CLAUDE.md").read_text(encoding="utf-8")
        drifted = raw.replace("index", "INDEX-CHANGED")  # inside the block
        (mb / "CLAUDE.md").write_text(drifted, encoding="utf-8")
        if check_quiet(mb) != 1:
            failures.append("a managed-block digest drift expected exit 1")
        mb2 = _fresh("mblock2")
        raw2 = (mb2 / "CLAUDE.md").read_text(encoding="utf-8")
        (mb2 / "CLAUDE.md").write_text(raw2.replace("tail", "tail changed outside the block"),
                                       encoding="utf-8")
        if check_quiet(mb2) != 0:
            failures.append("a surroundings-only CLAUDE.md change (block unchanged) expected exit 0")

        # (h) an order record disagreeing with the operative constants -> exit 1.
        od = _fresh("order")
        (od / ".aiqt" / "core").mkdir(parents=True, exist_ok=True)
        (od / ".aiqt" / "core" / "order.toml").write_text(
            'format-version = 1\napex-corpus-id = "prjint1"\n\n'
            '[[precedence-tier]]\nrank = 10\nmembers = ["ACCUR"]\nmembers-are-equal = true\n\n'
            '[presentation-order]\nsecurity-facets = ["SECC", "SECI", "SECA", "SECP"]\n',
            encoding="utf-8")
        gen_quiet(od)  # regenerate so the SOURCES hash matches; isolate leg 11 (order consistency)
        if check_quiet(od) != 1:
            failures.append("an order record disagreeing with gen_rules constants expected exit 1")

        # (i) F-237: an unknown TOP-LEVEL key in each record fails closed (exit 2). Regenerate after the
        #     edit so the SOURCES hash matches and it is the schema check that fires, not a byte drift.
        ok = _fresh("orderkey")
        (ok / ".aiqt" / "core" / "order.toml").write_text(
            gm._ORDER.replace('apex-corpus-id = "prjint1"\n', 'apex-corpus-id = "prjint1"\nstray = 1\n', 1),
            encoding="utf-8")
        gen_quiet(ok)
        if check_quiet(ok) != 2:
            failures.append("F-237: an unknown top-level key in order.toml expected exit 2")
        rk = _fresh("refkey")
        (rk / ".aiqt" / "core" / "references.toml").write_text(
            gm._REFERENCES.replace("quorum = 1\n", "quorum = 1\nquroum = 1\n", 1), encoding="utf-8")
        gen_quiet(rk)
        if check_quiet(rk) != 2:
            failures.append("F-237: an unknown top-level key (a quroum typo) in references.toml expected "
                            "exit 2")
        dk = _fresh("dispkey")
        (dk / ".aiqt" / "core" / "dispositions.toml").write_text(gm._DISPOSITIONS + "stray = 1\n",
                                                                 encoding="utf-8")
        gen_quiet(dk)
        if check_quiet(dk) != 2:
            failures.append("F-237: an unknown top-level key in dispositions.toml expected exit 2")

        # (j) F-237 / 5.3: an unsatisfiable quorum (2 with a single independent pipeline) fails closed.
        q = _fresh("quorum")
        (q / ".aiqt" / "core" / "references.toml").write_text(
            gm._REFERENCES.replace("quorum = 1", "quorum = 2"), encoding="utf-8")
        gen_quiet(q)
        if check_quiet(q) != 2:
            failures.append("F-237: an unsatisfiable quorum (> distinct independent pipelines) expected "
                            "exit 2")

        # (k) F-236 (defence in depth): check_manifest independently rejects an output at index mode
        #     100755. Track the generated outputs at 100644 (clean), then chmod one executable and re-stage
        #     so its index mode is 100755 -> exit 2.
        cmmode = _fresh("cm-outmode")
        gm._git(cmmode, "add", "-A")
        if check_quiet(cmmode) != 0:
            failures.append("F-236: a tracked 100644 output set expected a clean check (exit 0)")
        os.chmod(cmmode / gm.MANIFEST_REL, 0o755)
        gm._git(cmmode, "add", gm.MANIFEST_REL)
        if check_quiet(cmmode) != 2:
            failures.append("F-236: check_manifest independently rejects an output at index mode 100755 "
                            "(exit 2)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if failures:
        print("SELF-TEST FAIL:")
        for failure in failures:
            print("  - " + failure)
        return 1
    print("SELF-TEST PASS: a clean fixture verifies; a wrong SOURCES byte and a missing SOURCES row are "
          "well-formed disagreements (exit 1); a below-minimum class, a genesis flag beside a non-empty "
          "releases record, a symlinked and a hard-linked SOURCES member, and an alias-gate duplicate "
          "pipeline-id all fail closed (exit 2); a managed-block digest drift is exit 1 while a "
          "surroundings-only change is clean; an order record disagreeing with the operative "
          "gen_rules constants is exit 1; an unknown top-level key in the order, references, or "
          "dispositions record and an unsatisfiable quorum each fail closed (exit 2, F-237); and "
          "check_manifest independently rejects an output at git index mode 100755 (exit 2, F-236)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
