#!/usr/bin/env python3
"""Crosswalk candidate generator and shipped schema reference (VER-CORE 7.5, 8.2, 8.6). Stdlib only.

REPO mode (default, or --check): (re)generate .aiqt/core/migration/crosswalk-schema.toml, the adopter-
facing schema reference, deterministically from the constants in this file, drift-gated like every
generator (its GENSRC_OUTPUTS declaration is discovered by gen_gensrc.py, so this tool cannot land
without declaring its output). The runtime adopter crosswalk.toml is NEVER a registry target.

ADOPTER mode (--legacy-root DIR [--out .aiqt/migration]): build CANDIDATE crosswalk material for a human
reviewer. Order is load-bearing (8.2, spec lines 1227 to 1234): each legacy file's RAW BYTES are archived
FIRST under <out-archive>/.aiqt/archive/<sha256>/payload (immutable: re-archiving differing bytes under
the same name is refused), BEFORE any pointer handling. Embedded pointers REMAIN verbatim in the
immutable raw archived bytes; the tool never INJECTS a parsed or derived pointer annotation into an
archived payload. The tool then emits candidate predecessor rows and pointer-
ranked candidate mapping rows with EMPTY review/verdict fields plus an explicitly computed unmatched
list. It NEVER auto-asserts semantic equivalence (8.5) or enumeration completeness (8.2): a pointer
(Expected-successor: / Coverage:) is a hint with zero evidentiary weight that only RANKS candidates.

Exit convention (matches the repo's gates): 0 clean; 1 drift (--check) or a refused adopter precondition;
2 malformed input, a read error, or an archive immutability violation.
"""
import hashlib
import os
import re
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _gen_common import repo_root, reconcile  # noqa: E402

SCHEMA_REL = ".aiqt/core/migration/crosswalk-schema.toml"

GENSRC_OUTPUTS = (
    {"target": ".aiqt/core/migration/crosswalk-schema.toml", "kind": "file",
     "sources": ("tools/gen_crosswalk.py",), "regenerate": "python3 tools/gen_crosswalk.py"},
)

# The verbatim schema-reference body. A single source of truth rendered byte-for-byte, so the drift gate
# and the fail-close sweep cover the adopter-facing schema. Sentence-cased, no en or em dashes.
_SCHEMA_BODY = '''# AIQT Guardrails: adopter crosswalk schema reference (VER-CORE 8.x)
# GENERATED by tools/gen_crosswalk.py; do not hand-edit. This file DOCUMENTS the schema of the runtime
# adopter file .aiqt/migration/crosswalk.toml; it is not itself a crosswalk. The runtime crosswalk is
# adopter-state (never a manifest set-equality member). Every verdict field is HUMAN-JUDGMENT: the
# check_crosswalk gate proves the fields are present, well-formed, and name a distinct reviewer and a
# distinct family, never that a real cross-family review occurred.
schema-version = 1

# [target-release]: the release the migration maps TO (the pinned successor inventory).
#   version, tag-object-sha, commit-sha, root, clause-inventory-digest

# [[archive-file]]: one row per archived legacy file (immutable, 8.2).
#   legacy-path, archive-sha256 (also the archive directory name), size, mode, owner,
#   predecessor-clause-ids (the predecessor ids segmented out of this archived file)

# [enumeration-review]: 8.2 completeness attestation (HUMAN-JUDGMENT).
#   enumerator, enumerator-family, verdict = "complete", rationale,
#   reviewer (MUST differ from enumerator), reviewer-family, reviewed-utc

# [[predecessor]]: mirrors the 7.2 clause-inventory row over the ARCHIVED file (8.2 lines 1164 to 1168).
#   clause-id (the 8.3 pre-<archive-hash-prefix>.<ordinal> namespace, unpadded), archive-sha256,
#   start-line, end-line, canonical-text, source-digest (= the whole archived file's archive-sha256)

# [[mapping]]: one row PER successor, folds and splits included (8.6 lines 1223 to 1226).
#   predecessor-clause-id, successor-clause-id, successor-quote (a verbatim contiguous substring of the
#   successor clause's canonical text, 8.4), author, author-family,
#   semantic-verdict = "equal-or-stronger", rationale,
#   reviewer (MUST differ from author; family MUST differ), reviewer-family, reviewed-utc

# [[pointer-hint]]: an in-file pointer mirrored for the reviewer; a hint only, zero evidentiary weight.
#   predecessor-clause-id, expected-successor-ids, coverage, carrier = "frontmatter" | "body"
'''

# Pointer grammar (8.6 lines 1206 to 1210): greppable hints carried in frontmatter or body.
_EXPECTED_RE = re.compile(r"Expected-successor:\s*(.+)")
_COVERAGE_RE = re.compile(r"Coverage:\s*(.+)")
# A candidate paragraph splitter for predecessor segmentation (headings and blank-line-delimited blocks).
_PARA_SPLIT = re.compile(r"\n\s*\n")


def render_schema():
    return _SCHEMA_BODY


def run_repo(root, check):
    if not check:
        (root / SCHEMA_REL).parent.mkdir(parents=True, exist_ok=True)
    drifted = reconcile(root / SCHEMA_REL, render_schema(), check)   # fail-closes (exit 2) on I/O error
    if not check:
        print("wrote {}".format(SCHEMA_REL))
        return 0
    if drifted:
        print("drift: {} is out of date; run tools/gen_crosswalk.py".format(SCHEMA_REL), file=sys.stderr)
        return 1
    return 0


# --- adopter mode: archive-first candidate generation -------------------------------------------------

class AdoptError(Exception):
    """A refused adopter precondition or an archive immutability violation: fail-closed."""


def _toml_str(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def archive_file(archive_root, data):
    """Archive raw bytes under <archive_root>/<sha256>/payload, immutably. Returns the sha256. Refuses
    (AdoptError) if an existing entry under the same hash holds DIFFERING bytes (8.2 immutability); an
    identical re-archive is idempotent. Content-addressing keeps the archive idempotent (identical bytes
    yield the same hash directory, so two writers of the same payload cannot disagree). The staged bytes
    go to a UNIQUE-PER-CALL temp in the entry dir (tempfile.mkstemp, so concurrent callers never share a
    temp name) and are published by a NO-OVERWRITE link (os.link fails if payload already exists), so an
    existence race COMPARES bytes and accepts only byte-equality rather than overwriting an already-
    published payload."""
    digest = hashlib.sha256(data).hexdigest()
    entry = Path(archive_root) / digest
    payload = entry / "payload"
    if payload.exists():
        existing = payload.read_bytes()
        if existing != data:
            raise AdoptError("archive immutability violation: {} already holds different bytes".format(
                payload))
        return digest
    entry.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(entry), prefix="payload.", suffix=".tmp")
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(data)
        try:
            os.link(str(tmp), str(payload))               # no-overwrite publish: fails if payload exists
        except FileExistsError:                           # lost a publish race: accept only byte-equality
            existing = payload.read_bytes()
            if existing != data:
                raise AdoptError("archive immutability violation: {} already holds different bytes"
                                 .format(payload))
    finally:
        try:
            os.unlink(str(tmp))
        except FileNotFoundError:
            pass
    return digest


def parse_pointers(text):
    """Extract (expected_successor_ids, coverage) pointer hints from a legacy file's text. A pointer is a
    HINT with zero evidentiary weight; an embedded pointer stays verbatim in the raw archived bytes, and
    the tool never INJECTS a parsed or derived pointer annotation into an archived payload."""
    expected = []
    for m in _EXPECTED_RE.finditer(text):
        expected += [tok.strip() for tok in re.split(r"[,\s]+", m.group(1).strip()) if tok.strip()]
    cov = ""
    mc = _COVERAGE_RE.search(text)
    if mc:
        cov = mc.group(1).strip()
    return expected, cov


def _rank_candidates(pred_text, successor_texts):
    """Deterministic lexical-overlap ranking of successor candidates for a predecessor paragraph. Pure
    attention-ordering; it never fills a verdict and never waives review."""
    pred_tokens = set(re.findall(r"[a-z0-9]+", pred_text.lower()))
    scored = []
    for sid, stext in sorted(successor_texts.items()):
        stoks = set(re.findall(r"[a-z0-9]+", stext.lower()))
        overlap = len(pred_tokens & stoks)
        scored.append((-overlap, sid))
    scored.sort()
    return [sid for _, sid in scored]


def build_candidates(legacy_root, archive_root, successor_texts):
    """Archive every legacy file FIRST, then emit candidate predecessor rows, candidate mapping rows with
    EMPTY review fields, pointer hints, and the computed unmatched list. Deterministic ordering."""
    legacy_root = Path(legacy_root)
    files = sorted(p for p in legacy_root.rglob("*") if p.is_file())
    if not files:
        raise AdoptError("no legacy files under {}".format(legacy_root))
    archive_rows, predecessor_rows, mapping_rows, pointer_rows = [], [], [], []
    for f in files:
        data = f.read_bytes()                             # archive raw bytes FIRST (before any pointers)
        digest = archive_file(archive_root, data)
        rel = str(f.relative_to(legacy_root))
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            text = ""
        prefix = digest[:12]
        paras = [p for p in _PARA_SPLIT.split(text) if p.strip()] or [text]
        pred_ids = []
        for ordinal, para in enumerate(paras, start=1):
            pid = "pre-{}.{}".format(prefix, ordinal)
            pred_ids.append(pid)
            predecessor_rows.append({"clause-id": pid, "archive-sha256": digest,
                                     "canonical-text": para.strip(), "source-digest": digest})
            expected, coverage = parse_pointers(para)
            ranked = _rank_candidates(para, successor_texts)
            if expected or coverage:
                pointer_rows.append({"predecessor-clause-id": pid,
                                     "expected-successor-ids": expected, "coverage": coverage,
                                     "carrier": "body"})
            top = expected[:] if expected else ranked[:1]
            for sid in top:
                mapping_rows.append({"predecessor-clause-id": pid, "successor-clause-id": sid})
        archive_rows.append({"legacy-path": rel, "archive-sha256": digest, "size": len(data),
                             "predecessor-clause-ids": pred_ids})
    mapped = {m["predecessor-clause-id"] for m in mapping_rows}
    all_pred = {r["clause-id"] for r in predecessor_rows}
    unmatched = sorted(all_pred - mapped)
    return {"archive": archive_rows, "predecessor": predecessor_rows, "mapping": mapping_rows,
            "pointer": pointer_rows, "unmatched": unmatched}


def render_candidates(cand):
    """Render candidate crosswalk material as deterministic TOML with EMPTY review/verdict fields, so a
    human reviewer fills the judgment and a gate never sees a machine-asserted verdict."""
    out = ["# GENERATED CANDIDATE crosswalk (tools/gen_crosswalk.py --legacy-root). Review fields are",
           "# intentionally EMPTY: a human reviewer supplies every verdict. This tool asserts NOTHING.",
           "schema-version = 1", ""]
    for r in cand["archive"]:
        out += ["[[archive-file]]", "legacy-path = {}".format(_toml_str(r["legacy-path"])),
                "archive-sha256 = {}".format(_toml_str(r["archive-sha256"])),
                "size = {}".format(r["size"]),
                "predecessor-clause-ids = [{}]".format(
                    ", ".join(_toml_str(x) for x in r["predecessor-clause-ids"])), ""]
    for r in cand["predecessor"]:
        out += ["[[predecessor]]", "clause-id = {}".format(_toml_str(r["clause-id"])),
                "archive-sha256 = {}".format(_toml_str(r["archive-sha256"])),
                "canonical-text = {}".format(_toml_str(r["canonical-text"])),
                "source-digest = {}".format(_toml_str(r["source-digest"])), ""]
    for r in cand["mapping"]:
        out += ["[[mapping]]", "predecessor-clause-id = {}".format(_toml_str(r["predecessor-clause-id"])),
                "successor-clause-id = {}".format(_toml_str(r["successor-clause-id"])),
                'successor-quote = ""', 'author = ""', 'author-family = ""',
                'semantic-verdict = ""', 'rationale = ""', 'reviewer = ""', 'reviewer-family = ""',
                'reviewed-utc = ""', ""]
    for r in cand["pointer"]:
        out += ["[[pointer-hint]]",
                "predecessor-clause-id = {}".format(_toml_str(r["predecessor-clause-id"])),
                "expected-successor-ids = [{}]".format(
                    ", ".join(_toml_str(x) for x in r["expected-successor-ids"])),
                "coverage = {}".format(_toml_str(r["coverage"])),
                "carrier = {}".format(_toml_str(r["carrier"])), ""]
    out += ["# unmatched predecessors (computed; every one needs a reviewed mapping before check_crosswalk",
            "# can pass): [{}]".format(", ".join(_toml_str(x) for x in cand["unmatched"]))]
    return "\n".join(out) + "\n"


def run_adopter(legacy_root, out_dir, successor_texts):
    archive_root = Path(out_dir) / ".aiqt" / "archive"
    archive_root.mkdir(parents=True, exist_ok=True)
    try:
        cand = build_candidates(legacy_root, archive_root, successor_texts)
    except AdoptError as exc:
        print("error: {}; fail-closed".format(exc), file=sys.stderr)
        return 2 if "immutability" in str(exc) else 1
    migration_dir = Path(out_dir) / ".aiqt" / "migration"
    migration_dir.mkdir(parents=True, exist_ok=True)
    (migration_dir / "crosswalk.candidate.toml").write_text(render_candidates(cand), encoding="utf-8")
    print("wrote candidate crosswalk and {} archive entries under {}".format(
        len(cand["archive"]), out_dir))
    return 0


def main():
    args = sys.argv[1:]
    if "--self-test" in args:
        return self_test()
    if "--legacy-root" in args:
        legacy = Path(args[args.index("--legacy-root") + 1]).resolve()
        out = Path(args[args.index("--out") + 1]).resolve() if "--out" in args else legacy.parent
        return run_adopter(legacy, out, {})
    return run_repo(repo_root(), "--check" in args)


# --- self-test ----------------------------------------------------------------------------------------
# Proves the generator's own invariants over synthetic trees:
#   (a) REPO mode generates the schema reference, then re-checks drift-clean and is deterministic;
#   (b) a mutated schema reference fails --check (exit 1);
#   (c) ADOPTER mode archives every legacy file's RAW BYTES first, under the sha256 directory name;
#   (d) IMMUTABILITY: re-archiving DIFFERENT bytes under an existing hash is refused (exit 2), while an
#       identical re-archive is idempotent;
#   (e) pointer parsing extracts Expected-successor / Coverage hints and a pointer is never written into
#       an archived payload;
#   (f) the unmatched list is COMPUTED (a predecessor with no ranked or pointed successor is listed).

def self_test():
    import io
    import shutil
    import tempfile
    from contextlib import redirect_stdout, redirect_stderr

    def quiet(fn, *a, **k):
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            try:
                return fn(*a, **k)
            except SystemExit as exc:
                return "raised SystemExit({!r})".format(exc.code)

    try:
        tmp = Path(tempfile.mkdtemp(prefix="aiqt-gen-crosswalk-selftest-"))
    except OSError as exc:
        print("SELF-TEST ERROR: no writable temporary directory: {}".format(exc), file=sys.stderr)
        return 2
    failures = []
    try:
        # (a) REPO mode generate + drift-clean + determinism.
        good = tmp / "good"
        (good / ".aiqt" / "core" / "migration").mkdir(parents=True)
        if quiet(run_repo, good, False) != 0:
            failures.append("REPO generate expected exit 0")
        if quiet(run_repo, good, True) != 0:
            failures.append("REPO regeneration expected drift-clean exit 0")
        first = (good / SCHEMA_REL).read_text(encoding="utf-8")
        quiet(run_repo, good, False)
        if (good / SCHEMA_REL).read_text(encoding="utf-8") != first:
            failures.append("REPO mode is not deterministic")

        # (b) mutated schema -> exit 1.
        (good / SCHEMA_REL).write_text(first + "# tamper\n", encoding="utf-8")
        if quiet(run_repo, good, True) != 1:
            failures.append("a mutated schema reference expected exit 1 (drift)")

        # (c) ADOPTER archive-first: raw bytes under the sha256 dir name.
        legacy = tmp / "legacy"
        legacy.mkdir()
        body = "Old obligation text.\n\nExpected-successor: succ.1\nCoverage: full\n"
        (legacy / "rule.md").write_text(body, encoding="utf-8")
        out = tmp / "adopt"
        succ = {"succ.1": "The successor obligation text.", "succ.2": "Unrelated."}
        if quiet(run_adopter, legacy, out, succ) != 0:
            failures.append("ADOPTER mode expected exit 0")
        digest = hashlib.sha256(body.encode()).hexdigest()
        payload = out / ".aiqt" / "archive" / digest / "payload"
        if not payload.is_file() or payload.read_bytes() != body.encode():
            failures.append("ADOPTER mode did not archive the raw legacy bytes under its sha256")
        # (e) a pointer line is present in the source but the archived payload is the RAW file, unchanged.
        if b"Expected-successor" not in payload.read_bytes():
            failures.append("the archived payload must be the raw file (pointers not stripped from it)")
        cand_text = (out / ".aiqt" / "migration" / "crosswalk.candidate.toml").read_text(encoding="utf-8")
        if 'semantic-verdict = ""' not in cand_text:
            failures.append("candidate mapping rows must carry EMPTY verdict fields (asserts nothing)")

        # (d) immutability: differing re-archive refused; identical idempotent.
        archive_root = out / ".aiqt" / "archive"
        try:
            same = archive_file(archive_root, body.encode())
            if same != digest:
                failures.append("identical re-archive should be idempotent")
        except AdoptError:
            failures.append("identical re-archive should not be refused")
        # forge a differing payload under the same hash dir and confirm refusal
        forged = archive_root / digest / "payload"
        forged.write_bytes(b"tampered\n")
        try:
            archive_file(archive_root, body.encode())
            failures.append("re-archiving different bytes under an existing hash must be refused (exit 2)")
        except AdoptError:
            pass

        # (fix #7) unique-per-call temp + no-overwrite publish: a fresh archive leaves NO leftover temp in
        # its entry dir, publishes the exact bytes, and a same-bytes re-archive is idempotent.
        fresh = b"a distinct archive payload for the temp/link test\n"
        fdig = hashlib.sha256(fresh).hexdigest()
        arc7 = tmp / "arc7"
        d1 = archive_file(arc7, fresh)
        d2 = archive_file(arc7, fresh)                     # same-bytes re-archive is idempotent
        if d1 != fdig or d2 != fdig:
            failures.append("archive_file must be content-addressed and idempotent")
        entry7 = arc7 / fdig
        if (entry7 / "payload").read_bytes() != fresh:
            failures.append("the published payload must be the exact archived bytes")
        leftover = [p.name for p in entry7.iterdir() if p.name != "payload"]
        if leftover:
            failures.append("archive_file must leave no temp files behind (found {})".format(leftover))

        # (f) unmatched computed: a predecessor with no overlap and no pointer is listed unmatched.
        legacy2 = tmp / "legacy2"
        legacy2.mkdir()
        (legacy2 / "x.md").write_text("zzz qqq wthismatchesnothing\n", encoding="utf-8")
        cand = build_candidates(legacy2, tmp / "arc2", {})    # empty successor set -> nothing to map
        if not cand["unmatched"]:
            failures.append("a predecessor with no mappable successor must appear in the unmatched list")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if failures:
        print("SELF-TEST FAIL:")
        for f in failures:
            print("  - " + f)
        return 1
    print("SELF-TEST PASS: REPO mode generates the schema reference and regenerates drift-clean and "
          "deterministically (a mutation fails --check); ADOPTER mode archives every legacy file's RAW "
          "bytes FIRST under its sha256 (pointers are never stripped from the archived payload), emits "
          "candidate mapping rows with EMPTY verdict fields, refuses a differing re-archive under an "
          "existing hash while an identical one is idempotent, and computes the unmatched list.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
