#!/usr/bin/env python3
"""Generate the AIQT rule index from the .aiqt/core/rules/ sources.

The rule corpus index is a standalone GENERATED file, .claude/RULES-INDEX.md (titles + links into the
generated .claude/rules/ tree, grouped by facet in AIQT priority order). CLAUDE.md stays a hand-authored
governance file carrying ONE small generated marker block that POINTS to that index, so the governance
file is lean and human-authored end to end and can no longer silently duplicate or drift from the pack.
The full rule text loads into a Claude Code session via the .claude/rules/ tree (generated by
gen_rules.py). Both the standalone index and the CLAUDE.md pointer block are regenerated here and
drift-gated in CI; the hand-authored governance around the pointer block is human-reviewed as before.

  gen_claude.py           regenerate .claude/RULES-INDEX.md and the CLAUDE.md pointer block
  gen_claude.py --check    exit 0 clean, 1 on drift (run gen_claude.py to regenerate), 2 on malformed corpus
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _gen_common import repo_root, reconcile  # noqa: E402
from gen_rules import load_corpus  # noqa: E402
from gen_agents import sort_key  # noqa: E402

MARKER = "RULES-INDEX"
BEGIN = "<!-- {}:BEGIN (generated) -->".format(MARKER)
END = "<!-- {}:END -->".format(MARKER)
INDEX_PATH = ".claude/RULES-INDEX.md"

# facet -> group heading, in the order groups are emitted (apex first, then AIQT tiers, then security).
# The security family (SECC/SECI/SECA/SECP) collapses to one "Security" group, matching AGENTS.md's
# single security section; within it the rules keep their SECC/SECI/SECA/SECP sort order.
GROUPS = [
    ("__apex__", "Apex"),
    ("ACCUR", "Accuracy"),
    ("INTEG", "Integrity"),
    ("QUALI", "Quality"),
    ("TRUST", "Trust"),
    ("PROGR", "Progress"),
    ("SPEED", "Speed"),
    ("COST", "Cost"),
    ("__security__", "Security"),
]
GROUP_ORDER = {key: i for i, (key, _label) in enumerate(GROUPS)}
GROUP_LABEL = {key: label for key, label in GROUPS}

# Declares this generator's outputs for the gensrc registry (tools/gen_gensrc.py); additive metadata only,
# it does not affect what this generator produces. The standalone index .claude/RULES-INDEX.md is a whole
# generated file (kind file); the CLAUDE.md pointer is a generated region inside the hand-authored
# governance file (kind block, the RULES-INDEX markers).
GENSRC_OUTPUTS = (
    {"target": ".claude/RULES-INDEX.md", "kind": "file",
     "sources": (".aiqt/core/rules/",), "regenerate": "python3 tools/gen_claude.py"},
    {"target": "CLAUDE.md", "kind": "block",
     "sources": (".aiqt/core/rules/",), "regenerate": "python3 tools/gen_claude.py"},
)


def _group_key(fm):
    """The index group a rule belongs to: apex, its AIQT facet, or the single security group."""
    if fm.get("apex") is True:
        return "__apex__"
    if fm["family"] == "security":
        return "__security__"
    return fm.get("facet", "")


def title_of(path):
    """The rule's H1 title (the first '# ' line of the body, after the frontmatter). Raises ValueError
    if the body has no H1, so a malformed rule fails closed rather than emitting a blank index entry."""
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---\n", 4)
    body = text[end + 5:].strip() if end != -1 else text.strip()
    first = body.splitlines()[0] if body else ""
    if not first.startswith("# "):
        raise ValueError("{}: rule body has no '# ' H1 title".format(path.name))
    return first[2:].strip()


def _index_lines(corpus, link_prefix):
    """The grouped index entries. link_prefix is prepended to each rule's rel path so links resolve from
    the host file's directory (repo root uses '.claude/rules/', the .claude/ index file uses 'rules/')."""
    items = sorted(corpus, key=lambda pfr: (GROUP_ORDER.get(_group_key(pfr[1]), 99), sort_key(pfr[1])))
    lines = []
    current = None
    for path, fm, rel in items:
        gk = _group_key(fm)
        link = "[{}]({}{})".format(title_of(path), link_prefix, rel)
        if gk == "__apex__":
            lines.append("**{}** - {}".format(GROUP_LABEL[gk], link))
            current = gk
            continue
        if gk != current:
            lines.append("")  # a blank line separates each facet group from the previous one
            lines.append("**{}**".format(GROUP_LABEL[gk]))
            current = gk
        lines.append("- " + link)
    return lines


def render_indexdoc(corpus):
    """The standalone .claude/RULES-INDEX.md content. Links resolve from .claude/ (prefix 'rules/')."""
    lines = [
        "# AIQT rule index",
        "",
        "Generated from `.aiqt/core/rules/` by `tools/gen_claude.py` and drift-gated in CI; do not "
        "hand-edit. The full rule text loads from `.claude/rules/` (also generated, by "
        "`tools/gen_rules.py`). Rules are grouped by facet in AIQT priority order.",
        "",
    ]
    lines += _index_lines(corpus, "rules/")
    return "\n".join(lines).rstrip() + "\n"


def render_pointer():
    """The CLAUDE.md pointer block inner text (between the markers). Points at the standalone index."""
    return "\n".join([
        "## AIQT rule index",
        "",
        "The rule corpus is indexed in [.claude/RULES-INDEX.md](.claude/RULES-INDEX.md), grouped by facet "
        "in AIQT priority order, and the full rule text loads from `.claude/rules/`. Both are generated "
        "from `.aiqt/core/rules/` (by `tools/gen_claude.py` and `tools/gen_rules.py`) and drift-gated in "
        "CI; do not hand-edit this block or the index file.",
    ])


def replace_block(text, inner):
    """Replace the content between the markdown markers, keeping the markers on their own lines."""
    i = text.find(BEGIN)
    j = text.find(END)
    if i == -1 or j == -1 or j < i:
        raise ValueError("RULES-INDEX markers not found in CLAUDE.md")
    return text[:i] + BEGIN + "\n" + inner + "\n" + text[j:]


def main():
    check = "--check" in sys.argv[1:]
    root = repo_root()
    src_dir = root / ".aiqt" / "core" / "rules"
    claude_md = root / "CLAUDE.md"
    index_md = root / INDEX_PATH
    if not claude_md.exists():
        print("error: CLAUDE.md not found at {}".format(claude_md), file=sys.stderr)
        return 2
    try:
        corpus = load_corpus(src_dir)
        indexdoc = render_indexdoc(corpus)
        current = claude_md.read_text(encoding="utf-8")
        new_claude = replace_block(current, render_pointer())
    except (ValueError, OSError) as exc:
        print("error: {}".format(exc), file=sys.stderr)
        return 2
    drift = False
    if reconcile(index_md, indexdoc, check):
        print("drift: {}".format(INDEX_PATH))
        drift = True
    if reconcile(claude_md, new_claude, check):
        print("drift: CLAUDE.md")
        drift = True
    if drift:
        print("run tools/gen_claude.py to regenerate")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
