#!/usr/bin/env python3
"""Crosswalk candidate generator and shipped schema reference (VER-CORE 7.5, 8.2, 8.6). Stdlib only.

REPO mode (default, or --check): (re)generate .aiqt/core/migration/crosswalk-schema.toml, the adopter-
facing schema reference, deterministically from the constants in this file, drift-gated like every
generator (its GENSRC_OUTPUTS declaration is discovered by gen_gensrc.py, so this tool cannot land
without declaring its output). The runtime adopter crosswalk.toml is NEVER a registry target.

ADOPTER mode (--legacy-root DIR [--out .aiqt/migration]): build CANDIDATE crosswalk material for a human
reviewer. Order is load-bearing (8.2, spec lines 1227 to 1234): each legacy file's RAW BYTES are archived
FIRST under <out-archive>/.aiqt/archive/<sha256>/payload (immutable: re-archiving differing bytes under
the same name is refused), BEFORE any pointer handling. The tool never INJECTS a parsed or derived pointer
annotation into an archived payload; the archive is always the legacy file's raw bytes verbatim. The tool
then emits candidate predecessor rows (with computable 7.2 spans) and pointer-ranked candidate mapping rows
with EMPTY review/verdict fields plus an explicitly computed unmatched list. It NEVER auto-asserts semantic
equivalence (8.5) or enumeration completeness (8.2): a pointer (Expected-successor: / Coverage:) is a hint
with zero evidentiary weight that only RANKS candidates.

DISCLOSED (D10, spec 8.6 lines 1236 to 1243, tracked post-VC-6 follow-up): 8.6 mandates that a pointer live
ONLY in the adopter's migration state and that the archived PREIMAGE always be the UNANNOTATED predecessor
bytes. This tool archives the legacy raw bytes verbatim (correct per 8.2) BUT reads pointer HINTS from those
same archived bytes, i.e. it assumes any pointer is embedded in the legacy source. Reconciling this to 8.6's
migration-state-only pointer carriage is a larger redesign (predecessor clause-ids are GENERATED here, so a
migration-state pointer carrier keyed by clause-id is a chicken-and-egg the adopter workflow must resolve),
deferred out of the VC-6 slice. Until then, an "Expected-successor:" line in a legacy file is treated as an
incidental hint, NOT the spec's migration-state pointer; this tool does not claim section 8.6 pointer-carriage
conformance, and migration-state pointer carriage is deferred out of the VC-6 slice (to Step 7).

Exit convention (matches the repo's gates): 0 clean; 1 drift (--check) or a refused adopter precondition;
2 malformed input, a read error, or an archive immutability violation.
"""
import hashlib
import itertools
import os
import re
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _gen_common import repo_root, reconcile  # noqa: E402

SCHEMA_REL = ".aiqt/core/migration/crosswalk-schema.toml"

GENSRC_OUTPUTS = (
    {"target": ".aiqt/core/migration/crosswalk-schema.toml", "kind": "file",
     "sources": ("tools/gen_crosswalk.py",), "regenerate": "python3 tools/gen_crosswalk.py"},
)

# The verbatim schema-reference body. A single source of truth rendered byte-for-byte, so the drift gate
# and the fail-close sweep cover the adopter-facing schema. Sentence-cased, no en or em dashes.
_SCHEMA_BODY = '''# AIQT Guardrails: adopter crosswalk schema reference (VER-CORE 8.x)
# GENERATED by tools/gen_crosswalk.py; do not hand-edit. This file DOCUMENTS the schema of the runtime
# adopter file .aiqt/migration/crosswalk.toml; it is not itself a crosswalk. The runtime crosswalk is
# adopter-state (never a manifest set-equality member). Every verdict field is HUMAN-JUDGMENT: the
# check_crosswalk gate proves the fields are present, well-formed, and name a distinct reviewer and a
# distinct family, never that a real cross-family review occurred.
schema-version = 1

# [target-release]: the release the migration maps TO (the pinned successor inventory).
#   version, tag-object-sha, commit-sha, root, clause-inventory-digest

# [[archive-file]]: one row per archived legacy file (immutable, 8.2).
#   legacy-path, archive-sha256 (also the archive directory name), size, owner,
#   predecessor-clause-ids (the predecessor ids segmented out of this archived file)

# [enumeration-review]: 8.2 completeness attestation (HUMAN-JUDGMENT).
#   enumerator, enumerator-family, verdict = "complete", rationale,
#   reviewer (MUST differ from enumerator), reviewer-family, reviewed-utc

# [[predecessor]]: mirrors the 7.2 clause-inventory row over the ARCHIVED file (8.2 lines 1164 to 1168).
#   clause-id (the 8.3 pre-<archive-hash-prefix>.<ordinal> namespace, unpadded), archive-sha256,
#   start-line, end-line, canonical-text, source-digest (= the whole archived file's archive-sha256)

# [[mapping]]: one row PER successor, folds and splits included (8.6 lines 1223 to 1226).
#   predecessor-clause-id, successor-clause-id, successor-quote (a verbatim contiguous substring of the
#   successor clause's canonical text, 8.4), author, author-family,
#   semantic-verdict = "equal-or-stronger", rationale,
#   reviewer (MUST differ from author; family MUST differ), reviewer-family, reviewed-utc

# [[pointer-hint]]: an in-file pointer mirrored for the reviewer; a hint only, zero evidentiary weight.
#   predecessor-clause-id, expected-successor-ids, coverage, carrier = "frontmatter" | "body"

# Section 8.6 pointer-carriage deferral (D10): this tool does not claim section 8.6 pointer-carriage
# conformance; migration-state pointer carriage is deferred out of the VC-6 slice (to Step 7). A pointer
# here is an incidental in-file hint, not the spec's migration-state pointer.
'''

# Pointer grammar (8.6 lines 1206 to 1210): greppable hints carried in frontmatter or body.
_EXPECTED_RE = re.compile(r"Expected-successor:\s*(.+)")
_COVERAGE_RE = re.compile(r"Coverage:\s*(.+)")
def _segment_paragraphs(text):
    """Segment text into (paragraph_text, start_line, end_line) blocks on blank-line boundaries, tracking
    1-based line numbers, so each candidate predecessor row can carry a tight 7.2 whole-line source span
    (start-line/end-line) over the archived bytes. Blank (whitespace-only) lines delimit; a paragraph is a
    maximal run of non-blank lines. An all-blank or empty file yields a single whole-file block."""
    lines = text.split("\n")
    blocks, i, nlines = [], 0, len(lines)
    while i < nlines:
        while i < nlines and lines[i].strip() == "":
            i += 1
        if i >= nlines:
            break
        start = i
        while i < nlines and lines[i].strip() != "":
            i += 1
        blocks.append(("\n".join(lines[start:i]), start + 1, i))   # end-line = i (1-based inclusive)
    if not blocks:
        return [(text, 1, max(1, nlines))]
    return blocks


def render_schema():
    return _SCHEMA_BODY


def run_repo(root, check):
    if not check:
        (root / SCHEMA_REL).parent.mkdir(parents=True, exist_ok=True)
    drifted = reconcile(root / SCHEMA_REL, render_schema(), check)   # fail-closes (exit 2) on I/O error
    if not check:
        print("wrote {}".format(SCHEMA_REL))
        return 0
    if drifted:
        print("drift: {} is out of date; run tools/gen_crosswalk.py".format(SCHEMA_REL), file=sys.stderr)
        return 1
    return 0


# --- adopter mode: archive-first candidate generation -------------------------------------------------

class AdoptError(Exception):
    """A refused adopter precondition or an archive immutability/read-safety violation: fail-closed. The
    exit_code is 1 for a refused precondition (a human-actionable input state) and 2 for malformed or
    unsafe input, an I/O error, or an unconfirmed durability guarantee."""

    def __init__(self, message, exit_code=2):
        super().__init__(message)
        self.exit_code = exit_code


def _toml_str(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def _open_dir_at(dir_fd, name, create):
    """G8/G9: open directory `name` beneath dir_fd through an O_DIRECTORY|O_NOFOLLOW handle so a symlinked
    component can never redirect the archive out of the tree, creating it first when `create`. When a new
    directory is created its parent (dir_fd) is fsynced so a crash cannot lose the just-created entry (G9),
    and a fsync failure is PROPAGATED as an AdoptError rather than swallowed (success is never reported on
    an unconfirmed durability guarantee). Returns the opened dir fd (caller closes). AdoptError on a
    symlinked component, a non-directory, an I/O error, or an unconfirmed fsync."""
    created = False
    if create:
        try:
            os.mkdir(name, dir_fd=dir_fd)
            created = True
        except FileExistsError:
            pass
        except OSError as exc:
            raise AdoptError("cannot create archive component {!r} ({}); fail-closed".format(name, exc))
    try:
        fd = os.open(name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=dir_fd)
    except OSError as exc:
        raise AdoptError("cannot open archive component {!r} through a no-follow handle ({}); a symlinked "
                         "component is refused".format(name, exc))
    if created:
        try:
            os.fsync(dir_fd)                              # G9: persist the newly-created directory entry
        except OSError as exc:
            os.close(fd)
            raise AdoptError("cannot fsync the parent after creating {!r} ({}); durability not confirmed, "
                             "fail-closed".format(name, exc))
    return fd


def _walk_components(base_fd, names, create):
    """G8/G9: descend `names` in turn beneath base_fd, every hop through _open_dir_at (O_NOFOLLOW per
    component, durable creation), so no symlinked ANCESTOR can redirect the path and each new directory is
    crash-durable. Returns the final dir fd; intermediate fds are closed and base_fd is left open.
    AdoptError (fail-closed) on any symlinked or unconfirmed component."""
    fd, close_prev = base_fd, False
    try:
        for name in names:
            nxt = _open_dir_at(fd, name, create)
            if close_prev:
                os.close(fd)
            fd, close_prev = nxt, True
    except BaseException:
        if close_prev:
            os.close(fd)
        raise
    return fd


def _read_payload_fd(entry_fd):
    """G8 (8.2): read the `payload` beneath entry_fd through a NO-FOLLOW handle and require a REGULAR file,
    so an archive immutability comparison can never read redirectable external bytes. Returns the payload
    bytes, or None when the payload is absent; AdoptError on a symlinked or non-regular payload."""
    try:
        pfd = os.open("payload", os.O_RDONLY | os.O_NOFOLLOW, dir_fd=entry_fd)
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise AdoptError("cannot open archived payload ({}); a symlinked payload is refused".format(exc))
    try:
        if not stat.S_ISREG(os.fstat(pfd).st_mode):
            raise AdoptError("archived payload is not a regular file")
        return _read_fd_all(pfd)
    finally:
        os.close(pfd)


_TMP_SEQ = itertools.count()


def _verify_published_payload(entry_fd, digest, tmp_stat):
    """G8: re-open the just-published `payload` beneath entry_fd through a NO-FOLLOW handle and confirm it is
    the SAME regular-file inode we wrote (st_dev/st_ino match the retained temp) whose bytes still hash to
    `digest`, BEFORE reporting success. So a concurrent writer who swaps the temp pathname for a symlink,
    or substitutes the payload between the write and the publish, fails closed rather than publishing a
    redirected or altered inode. AdoptError on a symlinked, non-regular, substituted, or mismatched payload."""
    try:
        pfd = os.open("payload", os.O_RDONLY | os.O_NOFOLLOW, dir_fd=entry_fd)
    except OSError as exc:
        raise AdoptError("cannot re-open the published payload through a no-follow handle ({}); a symlinked "
                         "payload is refused".format(exc))
    try:
        st = os.fstat(pfd)
        if not stat.S_ISREG(st.st_mode):
            raise AdoptError("published payload {}/payload is not a regular file".format(digest))
        if (st.st_dev, st.st_ino) != (tmp_stat.st_dev, tmp_stat.st_ino):
            raise AdoptError("published payload {}/payload is not the inode we wrote (concurrent substitution)"
                             .format(digest))
        if hashlib.sha256(_read_fd_all(pfd)).hexdigest() != digest:
            raise AdoptError("published payload {}/payload does not hash to its digest".format(digest))
    finally:
        os.close(pfd)


def _write_payload(entry_fd, digest, data):
    """Publish `data` as `payload` beneath entry_fd: write a UNIQUE-per-call temp (O_CREAT|O_EXCL|O_NOFOLLOW,
    so concurrent callers never share a name), fsync it, then publish by a NO-OVERWRITE, NO-FOLLOW link
    (os.link fails if payload already exists; follow_symlinks=False so a temp pathname a concurrent writer
    swapped for a symlink links the link itself, refused below, never its target inode), so a publish race
    COMPARES bytes and accepts only byte-equality rather than overwriting an already-published payload. On
    the winning branch the published payload is re-verified at source (same inode as the retained temp, same
    digest) before success is reported. The temp is always unlinked; entry_fd is fsynced so the published
    payload entry is durable. Every handle is dir_fd-relative and O_NOFOLLOW (G8)."""
    tmp_name = "payload.{}.{}.tmp".format(os.getpid(), next(_TMP_SEQ))
    tfd = os.open(tmp_name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600, dir_fd=entry_fd)
    try:
        with os.fdopen(tfd, "wb") as fh:
            fh.write(data)
            fh.flush()
            os.fsync(fh.fileno())                         # temp bytes durable BEFORE the atomic publish
            tmp_stat = os.fstat(fh.fileno())              # retain the temp inode BEFORE the fd closes
        try:
            os.link(tmp_name, "payload", src_dir_fd=entry_fd, dst_dir_fd=entry_fd,
                    follow_symlinks=False)                # no-overwrite, no-follow publish
        except FileExistsError:                           # lost a publish race: accept only byte-equality
            existing = _read_payload_fd(entry_fd)         # G8: no-follow read of the winner's payload
            if existing is None or existing != data:
                raise AdoptError("archive immutability violation: {}/payload already holds different bytes"
                                 .format(digest))
        else:                                             # we published: re-verify the linked payload at source
            _verify_published_payload(entry_fd, digest, tmp_stat)
    finally:
        try:
            os.unlink(tmp_name, dir_fd=entry_fd)
        except FileNotFoundError:
            pass
    os.fsync(entry_fd)                                    # durable published-payload directory entry


def archive_file(archive_fd, data):
    """Archive raw bytes as <archive_fd>/<sha256>/payload, immutably, ENTIRELY through dir_fd-relative
    O_NOFOLLOW handles beneath archive_fd (opened by run_adopter via a no-follow ANCESTOR walk), so neither
    a symlinked ancestor (.aiqt, archive) nor a symlinked hash-entry or payload can redirect the archive in
    or out of the tree (G8). Returns the sha256. Refuses (AdoptError) if an existing entry under the same
    hash holds DIFFERING bytes (8.2 immutability); an identical re-archive is idempotent. Content-addressing
    keeps the archive idempotent (identical bytes yield the same hash directory, so two writers of the same
    payload cannot disagree). The hash directory is created durably (G9) and the payload is published by a
    no-overwrite link (see _write_payload), so an existence race COMPARES bytes and accepts only
    byte-equality rather than overwriting an already-published payload."""
    digest = hashlib.sha256(data).hexdigest()
    try:
        entry_fd = os.open(digest, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=archive_fd)
    except FileNotFoundError:
        entry_fd = _open_dir_at(archive_fd, digest, create=True)  # mkdir + no-follow open + parent fsync (G8/G9)
    except OSError as exc:
        raise AdoptError("cannot open archive entry {} through a no-follow handle ({}); a symlinked entry "
                         "is refused".format(digest, exc))
    try:
        existing = _read_payload_fd(entry_fd)             # G8: no-follow payload read; None when absent
        if existing is not None:
            if existing != data:
                raise AdoptError("archive immutability violation: {}/payload already holds different bytes"
                                 .format(digest))
            os.fsync(entry_fd)                            # fix #7: durable on the idempotent early-exists return
            return digest
        _write_payload(entry_fd, digest, data)
        return digest
    finally:
        os.close(entry_fd)


def _read_fd_all(fd):
    chunks = []
    while True:
        block = os.read(fd, 1 << 20)
        if not block:
            break
        chunks.append(block)
    return b"".join(chunks)


def parse_pointers(text):
    """Extract (expected_successor_ids, coverage) pointer hints from a legacy file's text. A pointer is a
    HINT with zero evidentiary weight; an embedded pointer stays verbatim in the raw archived bytes, and
    the tool never INJECTS a parsed or derived pointer annotation into an archived payload."""
    expected = []
    for m in _EXPECTED_RE.finditer(text):
        expected += [tok.strip() for tok in re.split(r"[,\s]+", m.group(1).strip()) if tok.strip()]
    cov = ""
    mc = _COVERAGE_RE.search(text)
    if mc:
        cov = mc.group(1).strip()
    return expected, cov


def _rank_candidates(pred_text, successor_texts):
    """Deterministic lexical-overlap ranking of successor candidates for a predecessor paragraph. Pure
    attention-ordering; it never fills a verdict and never waives review."""
    pred_tokens = set(re.findall(r"[a-z0-9]+", pred_text.lower()))
    scored = []
    for sid, stext in sorted(successor_texts.items()):
        stoks = set(re.findall(r"[a-z0-9]+", stext.lower()))
        overlap = len(pred_tokens & stoks)
        scored.append((-overlap, sid))
    scored.sort()
    return [sid for _, sid in scored]


def build_candidates(legacy_root, archive_fd, successor_texts):
    """Archive every legacy file FIRST (beneath the no-follow-anchored archive_fd), then emit candidate
    predecessor rows, candidate mapping rows with EMPTY review fields, pointer hints, and the computed
    unmatched list. Deterministic ordering."""
    legacy_root = Path(legacy_root)
    files = sorted(p for p in legacy_root.rglob("*") if p.is_file())
    if not files:
        raise AdoptError("no legacy files under {}".format(legacy_root), exit_code=1)
    archive_rows, predecessor_rows, mapping_rows, pointer_rows = [], [], [], []
    for f in files:
        # fix #6: capture the 8.2 OWNER from the SAME opened source fd the raw bytes come from, so the
        # recorded owner cannot disagree with the archived payload. No O_NOFOLLOW here: legacy trees may
        # legitimately carry symlinked files that rglob(is_file) and the prior read_bytes both followed.
        fd = os.open(str(f), os.O_RDONLY)
        try:
            owner = os.fstat(fd).st_uid
            data = _read_fd_all(fd)                        # archive raw bytes FIRST (before any pointers)
        finally:
            os.close(fd)
        digest = archive_file(archive_fd, data)
        rel = str(f.relative_to(legacy_root))
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            text = ""
        prefix = digest[:12]
        blocks = _segment_paragraphs(text)
        pred_ids = []
        for ordinal, (para, start_line, end_line) in enumerate(blocks, start=1):
            pid = "pre-{}.{}".format(prefix, ordinal)
            pred_ids.append(pid)
            # emit the computable 7.2 whole-line span (start-line/end-line) the schema documents, so a
            # candidate predecessor row is span-checkable rather than span-omitting.
            predecessor_rows.append({"clause-id": pid, "archive-sha256": digest, "start-line": start_line,
                                     "end-line": end_line, "canonical-text": para.strip(),
                                     "source-digest": digest})
            expected, coverage = parse_pointers(para)
            ranked = _rank_candidates(para, successor_texts)
            if expected or coverage:
                pointer_rows.append({"predecessor-clause-id": pid,
                                     "expected-successor-ids": expected, "coverage": coverage,
                                     "carrier": "body"})
            top = expected[:] if expected else ranked[:1]
            for sid in top:
                mapping_rows.append({"predecessor-clause-id": pid, "successor-clause-id": sid})
        archive_rows.append({"legacy-path": rel, "archive-sha256": digest, "size": len(data),
                             "owner": owner, "predecessor-clause-ids": pred_ids})
    mapped = {m["predecessor-clause-id"] for m in mapping_rows}
    all_pred = {r["clause-id"] for r in predecessor_rows}
    unmatched = sorted(all_pred - mapped)
    return {"archive": archive_rows, "predecessor": predecessor_rows, "mapping": mapping_rows,
            "pointer": pointer_rows, "unmatched": unmatched}


def render_candidates(cand):
    """Render candidate crosswalk material as deterministic TOML with EMPTY review/verdict fields, so a
    human reviewer fills the judgment and a gate never sees a machine-asserted verdict."""
    out = ["# GENERATED CANDIDATE crosswalk (tools/gen_crosswalk.py --legacy-root). Review fields are",
           "# intentionally EMPTY: a human reviewer supplies every verdict. This tool asserts NOTHING.",
           "schema-version = 1", ""]
    for r in cand["archive"]:
        out += ["[[archive-file]]", "legacy-path = {}".format(_toml_str(r["legacy-path"])),
                "archive-sha256 = {}".format(_toml_str(r["archive-sha256"])),
                "size = {}".format(r["size"]),
                "owner = {}".format(r["owner"]),
                "predecessor-clause-ids = [{}]".format(
                    ", ".join(_toml_str(x) for x in r["predecessor-clause-ids"])), ""]
    for r in cand["predecessor"]:
        out += ["[[predecessor]]", "clause-id = {}".format(_toml_str(r["clause-id"])),
                "archive-sha256 = {}".format(_toml_str(r["archive-sha256"])),
                "start-line = {}".format(r["start-line"]),
                "end-line = {}".format(r["end-line"]),
                "canonical-text = {}".format(_toml_str(r["canonical-text"])),
                "source-digest = {}".format(_toml_str(r["source-digest"])), ""]
    for r in cand["mapping"]:
        out += ["[[mapping]]", "predecessor-clause-id = {}".format(_toml_str(r["predecessor-clause-id"])),
                "successor-clause-id = {}".format(_toml_str(r["successor-clause-id"])),
                'successor-quote = ""', 'author = ""', 'author-family = ""',
                'semantic-verdict = ""', 'rationale = ""', 'reviewer = ""', 'reviewer-family = ""',
                'reviewed-utc = ""', ""]
    for r in cand["pointer"]:
        out += ["[[pointer-hint]]",
                "predecessor-clause-id = {}".format(_toml_str(r["predecessor-clause-id"])),
                "expected-successor-ids = [{}]".format(
                    ", ".join(_toml_str(x) for x in r["expected-successor-ids"])),
                "coverage = {}".format(_toml_str(r["coverage"])),
                "carrier = {}".format(_toml_str(r["carrier"])), ""]
    out += ["# unmatched predecessors (computed; every one needs a reviewed mapping before check_crosswalk",
            "# can pass): [{}]".format(", ".join(_toml_str(x) for x in cand["unmatched"]))]
    return "\n".join(out) + "\n"


def _write_candidate(migration_fd, text):
    """Write crosswalk.candidate.toml beneath migration_fd through an O_NOFOLLOW handle (G8, so a symlinked
    candidate file cannot redirect the write) and fsync both the file and the directory entry (G9)."""
    fd = os.open("crosswalk.candidate.toml",
                 os.O_WRONLY | os.O_CREAT | os.O_TRUNC | os.O_NOFOLLOW, 0o644, dir_fd=migration_fd)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())
    os.fsync(migration_fd)


def run_adopter(legacy_root, out_dir, successor_texts):
    out_dir = Path(out_dir)
    try:
        os.makedirs(str(out_dir), exist_ok=True)          # the chosen output root is the trusted anchor
        root_fd = os.open(str(out_dir), os.O_RDONLY | os.O_DIRECTORY)
    except OSError as exc:
        print("error: cannot open output root {} ({}); fail-closed".format(out_dir, exc), file=sys.stderr)
        return 2
    try:
        # G8/G9: walk .aiqt/archive and .aiqt/migration beneath the output root through no-follow handles
        # (durable creation), so no symlinked ancestor can redirect the archive or the migration state, and
        # archive/publish everything beneath those anchored handles.
        archive_fd = _walk_components(root_fd, (".aiqt", "archive"), create=True)
        try:
            cand = build_candidates(legacy_root, archive_fd, successor_texts)
        finally:
            os.close(archive_fd)
        migration_fd = _walk_components(root_fd, (".aiqt", "migration"), create=True)
        try:
            _write_candidate(migration_fd, render_candidates(cand))
        finally:
            os.close(migration_fd)
    except AdoptError as exc:
        print("error: {}; fail-closed".format(exc), file=sys.stderr)
        return exc.exit_code
    finally:
        os.close(root_fd)
    print("wrote candidate crosswalk and {} archive entries under {}".format(
        len(cand["archive"]), out_dir))
    return 0


def main():
    args = sys.argv[1:]
    if "--self-test" in args:
        return self_test()
    if "--legacy-root" in args:
        legacy = Path(args[args.index("--legacy-root") + 1]).resolve()
        out = Path(args[args.index("--out") + 1]).resolve() if "--out" in args else legacy.parent
        return run_adopter(legacy, out, {})
    return run_repo(repo_root(), "--check" in args)


# --- self-test ----------------------------------------------------------------------------------------
# Proves the generator's own invariants over synthetic trees:
#   (a) REPO mode generates the schema reference, then re-checks drift-clean and is deterministic;
#   (b) a mutated schema reference fails --check (exit 1);
#   (c) ADOPTER mode archives every legacy file's RAW BYTES first, under the sha256 directory name;
#   (d) IMMUTABILITY: re-archiving DIFFERENT bytes under an existing hash is refused (exit 2), while an
#       identical re-archive is idempotent;
#   (e) pointer parsing extracts Expected-successor / Coverage hints and a pointer is never written into
#       an archived payload;
#   (f) the unmatched list is COMPUTED (a predecessor with no ranked or pointed successor is listed).

def self_test():
    import io
    import shutil
    import tempfile
    from contextlib import redirect_stdout, redirect_stderr

    def quiet(fn, *a, **k):
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            try:
                return fn(*a, **k)
            except SystemExit as exc:
                return "raised SystemExit({!r})".format(exc.code)

    try:
        tmp = Path(tempfile.mkdtemp(prefix="aiqt-gen-crosswalk-selftest-"))
    except OSError as exc:
        print("SELF-TEST ERROR: no writable temporary directory: {}".format(exc), file=sys.stderr)
        return 2
    failures = []
    try:
        # (a) REPO mode generate + drift-clean + determinism.
        good = tmp / "good"
        (good / ".aiqt" / "core" / "migration").mkdir(parents=True)
        if quiet(run_repo, good, False) != 0:
            failures.append("REPO generate expected exit 0")
        if quiet(run_repo, good, True) != 0:
            failures.append("REPO regeneration expected drift-clean exit 0")
        first = (good / SCHEMA_REL).read_text(encoding="utf-8")
        quiet(run_repo, good, False)
        if (good / SCHEMA_REL).read_text(encoding="utf-8") != first:
            failures.append("REPO mode is not deterministic")

        # (b) mutated schema -> exit 1.
        (good / SCHEMA_REL).write_text(first + "# tamper\n", encoding="utf-8")
        if quiet(run_repo, good, True) != 1:
            failures.append("a mutated schema reference expected exit 1 (drift)")

        # (c) ADOPTER archive-first: raw bytes under the sha256 dir name.
        legacy = tmp / "legacy"
        legacy.mkdir()
        body = "Old obligation text.\n\nExpected-successor: succ.1\nCoverage: full\n"
        (legacy / "rule.md").write_text(body, encoding="utf-8")
        out = tmp / "adopt"
        succ = {"succ.1": "The successor obligation text.", "succ.2": "Unrelated."}
        if quiet(run_adopter, legacy, out, succ) != 0:
            failures.append("ADOPTER mode expected exit 0")
        digest = hashlib.sha256(body.encode()).hexdigest()
        payload = out / ".aiqt" / "archive" / digest / "payload"
        if not payload.is_file() or payload.read_bytes() != body.encode():
            failures.append("ADOPTER mode did not archive the raw legacy bytes under its sha256")
        # (e) a pointer line is present in the source but the archived payload is the RAW file, unchanged.
        if b"Expected-successor" not in payload.read_bytes():
            failures.append("the archived payload must be the raw file (pointers not stripped from it)")
        cand_text = (out / ".aiqt" / "migration" / "crosswalk.candidate.toml").read_text(encoding="utf-8")
        if 'semantic-verdict = ""' not in cand_text:
            failures.append("candidate mapping rows must carry EMPTY verdict fields (asserts nothing)")
        # fix #6: the 8.2-required owner is captured from the source fd and emitted on the archive-file row.
        if "owner = {}".format(os.getuid()) not in cand_text:
            failures.append("archive-file rows must carry the 8.2 owner captured from the source fd")
        # G-hardening: candidate predecessor rows now carry computable 7.2 spans (start-line/end-line).
        if "start-line = " not in cand_text or "end-line = " not in cand_text:
            failures.append("candidate predecessor rows must emit computable 7.2 spans (start-line/end-line)")

        # (d) immutability: differing re-archive refused; identical idempotent.
        archive_root = out / ".aiqt" / "archive"
        afd = os.open(str(archive_root), os.O_RDONLY | os.O_DIRECTORY)
        try:
            same = archive_file(afd, body.encode())
            if same != digest:
                failures.append("identical re-archive should be idempotent")
        except AdoptError:
            failures.append("identical re-archive should not be refused")
        # forge a differing payload under the same hash dir and confirm refusal
        forged = archive_root / digest / "payload"
        forged.write_bytes(b"tampered\n")
        try:
            archive_file(afd, body.encode())
            failures.append("re-archiving different bytes under an existing hash must be refused (exit 2)")
        except AdoptError:
            pass
        os.close(afd)

        # (fix #7) unique-per-call temp + no-overwrite publish: a fresh archive leaves NO leftover temp in
        # its entry dir, publishes the exact bytes, and a same-bytes re-archive is idempotent.
        fresh = b"a distinct archive payload for the temp/link test\n"
        fdig = hashlib.sha256(fresh).hexdigest()
        arc7 = tmp / "arc7"
        arc7.mkdir()
        afd7 = os.open(str(arc7), os.O_RDONLY | os.O_DIRECTORY)
        d1 = archive_file(afd7, fresh)
        d2 = archive_file(afd7, fresh)                     # same-bytes re-archive is idempotent
        os.close(afd7)
        if d1 != fdig or d2 != fdig:
            failures.append("archive_file must be content-addressed and idempotent")
        entry7 = arc7 / fdig
        if (entry7 / "payload").read_bytes() != fresh:
            failures.append("the published payload must be the exact archived bytes")
        leftover = [p.name for p in entry7.iterdir() if p.name != "payload"]
        if leftover:
            failures.append("archive_file must leave no temp files behind (found {})".format(leftover))

        # (B1) post-publish verification: a payload SUBSTITUTED between the no-overwrite publish link and
        # the digest re-check is refused (fail-closed), never reported as a clean publish. The substitution
        # is injected by wrapping os.link so that immediately AFTER the real link publishes our temp inode,
        # <entry>/payload is repointed at DIFFERENT bytes (a distinct regular file); the post-publish
        # inode/digest re-check must then raise AdoptError. Without the re-check a swap sails to false success.
        b1bytes = b"b1 post-publish payload verification test\n"
        b1dig = hashlib.sha256(b1bytes).hexdigest()
        b1arc = tmp / "b1arc"
        b1arc.mkdir()
        b1fd = os.open(str(b1arc), os.O_RDONLY | os.O_DIRECTORY)
        real_link = os.link

        def _link_then_swap(src, dst, **kw):
            real_link(src, dst, **kw)                      # the real no-overwrite publish of our temp inode
            entry = b1arc / b1dig                          # then substitute a different-inode payload
            (entry / "payload").unlink()
            (entry / "evil").write_bytes(b"a different payload than we wrote\n")
            real_link(str(entry / "evil"), str(entry / "payload"))

        os.link = _link_then_swap
        try:
            archive_file(b1fd, b1bytes)
            failures.append("B1: a payload substituted after the publish link must be refused (fail-closed)")
        except AdoptError:
            pass
        finally:
            os.link = real_link
            os.close(b1fd)

        # (f) unmatched computed: a predecessor with no overlap and no pointer is listed unmatched.
        legacy2 = tmp / "legacy2"
        legacy2.mkdir()
        (legacy2 / "x.md").write_text("zzz qqq wthismatchesnothing\n", encoding="utf-8")
        arc2 = tmp / "arc2"
        arc2.mkdir()
        afd2 = os.open(str(arc2), os.O_RDONLY | os.O_DIRECTORY)
        cand = build_candidates(legacy2, afd2, {})            # empty successor set -> nothing to map
        os.close(afd2)
        if not cand["unmatched"]:
            failures.append("a predecessor with no mappable successor must appear in the unmatched list")

        # (G8) a SYMLINKED payload under an existing hash dir is refused (a following read would have
        # accepted redirectable external bytes as if immutable).
        g8bytes = b"g8 archive immutability under a no-follow read\n"
        g8dig = hashlib.sha256(g8bytes).hexdigest()
        g8arc = tmp / "g8arc"
        (g8arc / g8dig).mkdir(parents=True)
        g8ext = tmp / "g8-external"
        g8ext.write_bytes(g8bytes)                            # external bytes that MATCH, so a follow would pass
        os.symlink(str(g8ext), str(g8arc / g8dig / "payload"))
        g8fd = os.open(str(g8arc), os.O_RDONLY | os.O_DIRECTORY)
        try:
            archive_file(g8fd, g8bytes)
            failures.append("G8: a symlinked archived payload must be refused (no-follow), not accepted")
        except AdoptError:
            pass
        os.close(g8fd)

        # (G9) durable hierarchy creation: run_adopter into a FRESH out dir completes without error and the
        # archive/migration dirs and entries are present (best-effort: the parent fsyncs are not observable).
        g9legacy = tmp / "g9-legacy"
        g9legacy.mkdir()
        (g9legacy / "r.md").write_text("A legacy obligation for the durability test.\n", encoding="utf-8")
        g9out = tmp / "g9" / "nested" / "out"                 # several missing hierarchy components
        if quiet(run_adopter, g9legacy, g9out, {}) != 0:
            failures.append("G9: run_adopter into a fresh nested out dir must exit 0")
        if not (g9out / ".aiqt" / "archive").is_dir():
            failures.append("G9: the archive hierarchy must be present after run_adopter")
        g9entries = list((g9out / ".aiqt" / "archive").iterdir()) if (g9out / ".aiqt" / "archive").is_dir() else []
        if not g9entries:
            failures.append("G9: at least one archive entry must be present after run_adopter")

        # (G8 ancestor) a symlinked .aiqt ANCESTOR in the OUTPUT tree cannot redirect the archive: the
        # no-follow ancestor walk refuses it and run_adopter fails CLOSED (exit 2), never writing the
        # archive through the link to an external directory. A target-following mkdir/open would have
        # created the archive under the external target instead.
        g8anc_out = tmp / "g8anc-out"
        g8anc_out.mkdir()
        g8anc_ext = tmp / "g8anc-external"
        g8anc_ext.mkdir()
        os.symlink(str(g8anc_ext), str(g8anc_out / ".aiqt"))
        if quiet(run_adopter, g9legacy, g8anc_out, {}) != 2:
            failures.append("G8: a symlinked .aiqt ancestor in the output tree must fail closed (exit 2)")
        if list(g8anc_ext.iterdir()):
            failures.append("G8: nothing must be written through the symlinked .aiqt ancestor")

        # (G9) an injected fsync failure on a newly-created hierarchy parent makes run_adopter FAIL CLOSED
        # (exit 2), never reporting success on a swallowed durability failure: the fsync OSError propagates
        # as an AdoptError rather than being discarded. Only the FIRST fsync (the first hierarchy parent) is
        # failed and every later fsync succeeds, so a discard bug would otherwise sail past it to a false
        # success (this isolates the swallow, not a blanket fsync outage).
        g9fail_out = tmp / "g9fail" / "out"
        real_fsync = os.fsync
        g9state = {"first": True}

        def _boom_once(fd):
            if g9state["first"]:
                g9state["first"] = False
                raise OSError("injected fsync failure")
            return real_fsync(fd)

        os.fsync = _boom_once
        try:
            g9rc = quiet(run_adopter, g9legacy, g9fail_out, {})
        finally:
            os.fsync = real_fsync
        if g9rc != 2:
            failures.append("G9: an injected fsync failure must make run_adopter fail closed (exit 2)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if failures:
        print("SELF-TEST FAIL:")
        for f in failures:
            print("  - " + f)
        return 1
    print("SELF-TEST PASS: REPO mode generates the schema reference and regenerates drift-clean and "
          "deterministically (a mutation fails --check); ADOPTER mode archives every legacy file's RAW "
          "bytes FIRST under its sha256 (pointers are never stripped from the archived payload), emits "
          "candidate mapping rows with EMPTY verdict fields, refuses a differing re-archive under an "
          "existing hash while an identical one is idempotent, and computes the unmatched list. DISCLOSED: "
          "this tool does not claim section 8.6 pointer-carriage conformance; migration-state pointer "
          "carriage is deferred out of the VC-6 slice (to Step 7).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
