#!/usr/bin/env python3
"""Generate the RULES-INDEX block inside CLAUDE.md from the .aiqt/core/rules/ sources (DF-1, option 2).

CLAUDE.md stays a hand-authored governance file with ONE generated marker block: an index of the rule
corpus (titles + links into the generated .claude/rules/ tree), grouped by facet in AIQT priority order.
The index replaces the rule prose that used to be duplicated in CLAUDE.md, so the governance file can no
longer silently drift from the pack; the full rule text still loads into a Claude Code session via the
.claude/rules/ tree (generated by gen_rules.py). Only the block between the markers is generated; the
hand-authored governance around it is human-reviewed as before.

  gen_claude.py           regenerate the RULES-INDEX block in CLAUDE.md
  gen_claude.py --check    exit 0 clean, 1 on drift (run gen_claude.py to regenerate), 2 on malformed corpus
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _gen_common import repo_root, reconcile  # noqa: E402
from gen_rules import load_corpus  # noqa: E402
from gen_agents import sort_key  # noqa: E402

MARKER = "RULES-INDEX"
BEGIN = "<!-- {}:BEGIN (generated) -->".format(MARKER)
END = "<!-- {}:END -->".format(MARKER)

# facet -> group heading, in the order groups are emitted (apex first, then AIQT tiers, then security).
# The security family (SECC/SECI/SECA/SECP) collapses to one "Security" group, matching AGENTS.md's
# single security section; within it the rules keep their SECC/SECI/SECA/SECP sort order.
GROUPS = [
    ("__apex__", "Apex"),
    ("ACCUR", "Accuracy"),
    ("INTEG", "Integrity"),
    ("QUALI", "Quality"),
    ("TRUST", "Trust"),
    ("PROGR", "Progress"),
    ("SPEED", "Speed"),
    ("COST", "Cost"),
    ("__security__", "Security"),
]
GROUP_ORDER = {key: i for i, (key, _label) in enumerate(GROUPS)}
GROUP_LABEL = {key: label for key, label in GROUPS}


def _group_key(fm):
    """The index group a rule belongs to: apex, its AIQT facet, or the single security group."""
    if fm.get("apex") is True:
        return "__apex__"
    if fm["family"] == "security":
        return "__security__"
    return fm.get("facet", "")


def title_of(path):
    """The rule's H1 title (the first '# ' line of the body, after the frontmatter). Raises ValueError
    if the body has no H1, so a malformed rule fails closed rather than emitting a blank index entry."""
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---\n", 4)
    body = text[end + 5:].strip() if end != -1 else text.strip()
    first = body.splitlines()[0] if body else ""
    if not first.startswith("# "):
        raise ValueError("{}: rule body has no '# ' H1 title".format(path.name))
    return first[2:].strip()


def render_index(corpus):
    """Render the index inner text (between the markers) from load_corpus output [(path, fm, rel)]."""
    # Order the whole corpus by the shared sort_key (apex, AIQT tier/facet/slug, then security), so the
    # index matches .claude/rules/ and AGENTS.md exactly. Group boundaries follow that same order.
    items = sorted(corpus, key=lambda pfr: (GROUP_ORDER.get(_group_key(pfr[1]), 99), sort_key(pfr[1])))
    lines = [
        "## AIQT rule index (generated from .aiqt/core/rules/; do not hand-edit this block)",
        "",
        "Full rule text lives in `.claude/rules/` (also generated, by `tools/gen_rules.py`) and loads",
        "into a Claude Code session automatically; this index is regenerated by `tools/gen_claude.py`,",
        "and both are drift-gated in CI.",
        "",
    ]
    current = None
    for path, fm, rel in items:
        gk = _group_key(fm)
        link = "[{}](.claude/rules/{})".format(title_of(path), rel)
        if gk == "__apex__":
            lines.append("**{}** - {}".format(GROUP_LABEL[gk], link))
            current = gk
            continue
        if gk != current:
            lines.append("")  # a blank line separates each facet group from the previous one
            lines.append("**{}**".format(GROUP_LABEL[gk]))
            current = gk
        lines.append("- " + link)
    return "\n".join(lines).rstrip()


def replace_block(text, inner):
    """Replace the content between the markdown markers, keeping the markers on their own lines."""
    i = text.find(BEGIN)
    j = text.find(END)
    if i == -1 or j == -1 or j < i:
        raise ValueError("RULES-INDEX markers not found in CLAUDE.md")
    return text[:i] + BEGIN + "\n" + inner + "\n" + text[j:]


def main():
    check = "--check" in sys.argv[1:]
    root = repo_root()
    src_dir = root / ".aiqt" / "core" / "rules"
    claude_md = root / "CLAUDE.md"
    if not claude_md.exists():
        print("error: CLAUDE.md not found at {}".format(claude_md), file=sys.stderr)
        return 2
    try:
        corpus = load_corpus(src_dir)
        inner = render_index(corpus)
        current = claude_md.read_text(encoding="utf-8")
        new_text = replace_block(current, inner)
    except (ValueError, OSError) as exc:
        print("error: {}".format(exc), file=sys.stderr)
        return 2
    if reconcile(claude_md, new_text, check):
        print("drift: CLAUDE.md")
        print("run tools/gen_claude.py to regenerate")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
